### ISSUE TITLE
Condensing and escaping CEDAR into JSON file

### ISSUE THREAD

**Issue by kevinmichaelchen** [permitio/cedar-agent#19]
Hey, this is a wonderful library.

I actually just [packaged](https://github.com/teaxyz/pantry/pull/3168) it up into @teaxyz's ecosystem.

One thing I'm wondering is if there's a recommended workflow for formatting/stringifying real `.cedar` files into something resembling [`policies.json`](https://github.com/permitio/cedar-agent/blob/main/examples/policies.json)?

(I can probably hack together some convoluted bash script, but I'm wondering if there's a known CLI or a better way).

(I'm also iterating on a real-life example here:
https://github.com/kevinmichaelchen/cedar-learning/tree/main/examples/policies)

**Comment by kevinmichaelchen** [comment]
All Cedar policies can [compile down to JSON](https://docs.cedarpolicy.com/json-format.html).

Cedar Core supports External Syntax Trees (ESTs) [for Templates](https://github.com/cedar-policy/cedar/blob/v2.3.3/cedar-policy/src/api.rs#L1451-L1474) and [for Policies](https://github.com/cedar-policy/cedar/blob/v2.3.3/cedar-policy/src/api.rs#L1739-L1760). Their [CLI](https://github.com/cedar-policy/cedar/tree/v2.3.3/cedar-policy-cli) doesn't support converting policies to JSON, but if it did, I could see that as being useful to Cedar Agent.

**Comment by omer9564** [comment]
Hey @kevinmichaelchen , the content in the json object for policy in cedar-agent is simply the cedar policy string. 
For example the following cedar policy
```cedar
permit (
    principal == User::"12UA45",
    action == Action::"view",
    resource in Folder::"abc"
) when {
    context.tls_version == "1.3"
};
```
will be 
```json
{
"id":"random_id",
"content":"permit (\nprincipal == User::"12UA45",\naction == Action::"view",\nresource in Folder::"abc"\n) when {\ncontext.tls_version == "1.3"\n};"
}
```
As you can see it is simply wrapping it as a string.
We didn't use the "compiled json" because this crate intend to wrap the cedar crate and use the most simple interface.

Imagine you store your policy in a git repo, you would want to store the simple policy representation in the repo and not the compiled one.

Hope it answers your question 😄

**Comment by kevinmichaelchen** [comment]
Yeah, that makes sense. The AST doesn't exactly improve any ergonomics now that I think about it.

I guess doing it in Bash is kinda ugly, but [**I got it working**](https://github.com/kevinmichaelchen/cedar-learning#cedar_agent) 😅 

Thanks for responding - I can close this 👍🏼
