### ISSUE TITLE
unexpected HTML response

### ISSUE THREAD

**Issue by srenatus** [permitio/cedar-agent#5]
just playing with this, I ran into a surprising HTML response -- not surprising in its error, but rather that it wasn't JSON

```
% curl -X PUT -H "Content-Type: application/json" -d @./examples/policies.json http://localhost:8180/v1/policies/viewers-policy
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>422 Unprocessable Entity</title>
</head>
<body align="center">
    <div role="main" align="center">
        <h1>422: Unprocessable Entity</h1>
        <p>The request was well-formed but was unable to be followed due to semantic errors.</p>
        <hr />
    </div>
    <div role="contentinfo" align="center">
        <small>Rocket</small>
    </div>
</body>
</html>
%         
```

**Comment by orweis** [comment]
Thanks @srenatus !
@omer9564 will take a look into it.

**Comment by omer9564** [comment]
Hey @srenatus 

The [example/policies.json](https://github.com/permitio/cedar-agent/blob/94d70fef56eb5113f9d6c63b7554e6db206673b4/examples/policies.json) file has list of policies.
The `PUT /v1/policies/{policy_id}` is supposed to have only one policy in the body, this is because you can't have multiple `permit` / `forbid` rules with the same id. 
If you'd like to create multiple policies you can use the `PUT /v1/policies` API, this will replace your existing policies with the ones in the request body.
You can check out the [README](https://github.com/permitio/cedar-agent/blob/94d70fef56eb5113f9d6c63b7554e6db206673b4/README.md), it has examples usage instructions.

It is still an issue that the response is in HTML format, and we'll work on a fix, 
Thanks for pointing this out :)

**Comment by srenatus** [comment]
Thanks for your help. I'm afraid I wasn't expecting anything but an error of some sort -- I was intentionally throwing this at the wrong endpoint to see what would happen 🙃 It's just the HTML that surprised me. (Sorry for not having made this clear.)
